Repository tomjoyce1/SoftwareDesign_CS4445, pull requests merged in 2025-02, with the labels that each got.

#23 Nanda sonar qube+refactoring
  .github/workflows/build.yml
  .gitignore
  pom.xml
  sonar-project.properties
  src/main/java/Flight.java
  src/main/java/FlightCommand.java
  src/main/java/FlightFactory.java
  src/main/java/GameCommand.java
  src/main/java/InterceptorDispatcher.java
  src/main/java/LoggingInterceptor.java
  src/main/java/WeatherBroker.java
  src/main/java/WeatherStation.java
Labels: enhancement

#32 Update flight type descriptions for Passenger, Military, Cargo, and Private Flights
  src/main/java/Flight/FlightTypes/CargoFlight.java
  src/main/java/Flight/FlightTypes/MilitaryFlight.java
  src/main/java/Flight/FlightTypes/PassengerFlight.java
  src/main/java/Flight/FlightTypes/PrivateFlight.java
  src/test/java/AutomatedTest.java
Labels: bugfix, small

#35 Dara decorator branch
  src/main/java/Commands/FlightCommand/HoldCommand.java
  src/main/java/Commands/FlightCommand/LandCommand.java
  src/main/java/Commands/FlightCommand/TakeOffCommand.java
  src/main/java/Commands/GameCommand/CheckFlightStatusCommand.java
  src/main/java/Commands/GameCommand/ControlFlightCommand.java
  src/main/java/Commands/GameCommand/CreateFlightCommand.java
  src/main/java/Commands/GameCommand/ListFlightsCommand.java
  src/main/java/Commands/GameCommand/UpdateWeatherCommand.java
  src/main/java/Controllers/SimulatorController.java
  src/main/java/Factories/FlightFactory.java
  src/main/java/Main.java
  src/main/java/Models/Decorators/FlightDecorator.java
  src/main/java/Models/Decorators/FuelDecorator/FuelDecorator.java
  src/main/java/Models/Decorators/RadarDecorator/BasicRadarDisplay.java
  src/main/java/Models/Decorators/RadarDecorator/RadarDecorator.java
  src/main/java/Models/Decorators/RadarDecorator/RadarDisplay.java
  src/main/java/Models/Flight/Flight.java
  src/main/java/Models/Flight/FlightTypes/CargoFlight.java
  src/main/java/Models/Flight/FlightTypes/FlightType.java
  src/main/java/Models/Flight/FlightTypes/MilitaryFlight.java
  src/main/java/Models/Flight/FlightTypes/PassengerFlight.java
  src/main/java/Models/Flight/FlightTypes/PrivateFlight.java
  src/main/java/Models/SimulatorModel.java
  src/main/java/Models/States/FlightState.java
  src/main/java/Models/States/InAirState.java
  src/main/java/Models/States/LandingModeState.java
  src/main/java/Models/States/OnRunwayState.java
  src/main/java/Simulator.java
  src/main/java/Views/SimulatorView.java
  src/test/java/AutomatedTest.java
Labels: bugfix, large

#40 Tiernan automated tests
  .gitignore
  .vscode/settings.json
  pom.xml
  src/test/java/MainTest.java
  src/test/java/bookmarksTest/InterceptorDispatcherTest.java
  src/test/java/bookmarksTest/LoggingInterceptorTest.java
  src/test/java/commandsTest/flightCommandTest/HoldCommandTest.java
  src/test/java/commandsTest/flightCommandTest/LandCommandTest.java
  src/test/java/commandsTest/flightCommandTest/TakeOffCommandTest.java
  src/test/java/commandsTest/gameCommandTest/CheckFlightStatusCommandTest.java
  src/test/java/commandsTest/gameCommandTest/ControlFlightCommandTest.java
  src/test/java/commandsTest/gameCommandTest/CreateFlightCommandTest.java
  src/test/java/commandsTest/gameCommandTest/ListFlightsCommandTest.java
  src/test/java/commandsTest/gameCommandTest/QuitCommandTest.java
  src/test/java/commandsTest/gameCommandTest/UpdateWeatherCommandTest.java
  src/test/java/controllersTest/SimulatorControllerTest.java
  src/test/java/factoriesTest/FlightFactoryTest.java
  src/test/java/models/SimulatorModelTest.java
  src/test/java/models/decoratorsTest/FlightDecoratorTest.java
  src/test/java/models/decoratorsTest/fuelDecoratorTest/FuelDecoratorTest.java
  src/test/java/models/decoratorsTest/radarDecoratorTest/BasicRadarDisplayTest.java
  src/test/java/models/decoratorsTest/radarDecoratorTest/RadarDecoratorTest.java
  src/test/java/models/flightTest/FlightTest.java
  src/test/java/models/flightTest/flightTypes/CargoFlightTest.java
  src/test/java/models/flightTest/flightTypes/MilitaryFlightTest.java
  src/test/java/models/flightTest/flightTypes/PassengerFlightTest.java
  src/test/java/models/flightTest/flightTypes/PrivateFlightTest.java
  src/test/java/models/statesTest/InAirStateTest.java
  src/test/java/models/statesTest/LandingModeStateTest.java
  src/test/java/models/statesTest/OnRunwayStateTest.java
  src/test/java/views/SimulatorViewTest.java
  src/test/java/weatherPubSubTest/WeatherBrokerTest.java
  src/test/java/weatherPubSubTest/WeatherStationTest.java
  target/jacoco.exec
Labels: large

#41 Refactored code to fit best practices and resolved few maintainabilit…
  .github/workflows/build.yml
Labels: small

#42 Refactor test method signatures to remove access modifiers for consistency
  src/test/java/AutomatedTest.java
  src/test/java/MainTest.java
  src/test/java/bookmarksTest/InterceptorDispatcherTest.java
  src/test/java/bookmarksTest/LoggingInterceptorTest.java
  src/test/java/commandsTest/flightCommandTest/HoldCommandTest.java
  src/test/java/commandsTest/flightCommandTest/LandCommandTest.java
  src/test/java/commandsTest/flightCommandTest/TakeOffCommandTest.java
  src/test/java/commandsTest/gameCommandTest/CheckFlightStatusCommandTest.java
  src/test/java/commandsTest/gameCommandTest/ControlFlightCommandTest.java
  src/test/java/commandsTest/gameCommandTest/CreateFlightCommandTest.java
  src/test/java/commandsTest/gameCommandTest/ListFlightsCommandTest.java
  src/test/java/commandsTest/gameCommandTest/QuitCommandTest.java
  src/test/java/commandsTest/gameCommandTest/UpdateWeatherCommandTest.java
  src/test/java/controllersTest/SimulatorControllerTest.java
  src/test/java/factoriesTest/FlightFactoryTest.java
  src/test/java/models/SimulatorModelTest.java
  src/test/java/models/decoratorsTest/FlightDecoratorTest.java
  src/test/java/models/decoratorsTest/fuelDecoratorTest/FuelDecoratorTest.java
  src/test/java/models/decoratorsTest/radarDecoratorTest/BasicRadarDisplayTest.java
  src/test/java/models/decoratorsTest/radarDecoratorTest/RadarDecoratorTest.java
  src/test/java/models/flightTest/FlightTest.java
  src/test/java/models/flightTest/flightTypes/CargoFlightTest.java
  src/test/java/models/flightTest/flightTypes/MilitaryFlightTest.java
  src/test/java/models/flightTest/flightTypes/PassengerFlightTest.java
  src/test/java/models/flightTest/flightTypes/PrivateFlightTest.java
  src/test/java/views/SimulatorViewTest.java
  src/test/java/weatherPubSubTest/WeatherBrokerTest.java
  src/test/java/weatherPubSubTest/WeatherStationTest.java
Labels: small

#44 Nanda maintainability fix
  .gitignore
  .vscode/settings.json
  pom.xml
  src/main/java/bookmarks/InterceptorDispatcher.java
  src/main/java/commands/gamecommand/CheckFlightStatusCommand.java
  src/main/java/commands/gamecommand/ControlFlightCommand.java
  src/main/java/commands/gamecommand/CreateFlightCommand.java
  src/main/java/commands/gamecommand/ListFlightsCommand.java
  src/main/java/commands/gamecommand/QuitCommand.java
  src/main/java/commands/gamecommand/UpdateWeatherCommand.java
  src/main/java/controllers/SimulatorController.java
  src/main/java/logOutput/logfileOutput.log.lck
  src/main/java/models/decorators/radardecorator/BasicRadarDisplay.java
  src/main/java/models/states/InAirState.java
  src/main/java/models/states/LandingModeState.java
  src/main/java/models/states/OnRunwayState.java
  src/main/java/views/ConsoleLogger.java
  src/main/java/views/CustomFormatter.java
  src/main/java/views/SimulatorView.java
  src/main/java/weatherpubsub/WeatherStation.java
  src/test/java/bookmarksTest/InterceptorDispatcherTest.java
  src/test/java/bookmarksTest/LoggingInterceptorTest.java
  src/test/java/commandsTest/gameCommandTest/ControlFlightCommandTest.java
  src/test/java/commandsTest/gameCommandTest/CreateFlightCommandTest.java
  src/test/java/commandsTest/gameCommandTest/ListFlightsCommandTest.java
  src/test/java/commandsTest/gameCommandTest/QuitCommandTest.java
  src/test/java/commandsTest/gameCommandTest/UpdateWeatherCommandTest.java
  src/test/java/controllersTest/SimulatorControllerTest.java
  src/test/java/models/SimulatorModelTest.java
  src/test/java/models/decoratorsTest/radarDecoratorTest/BasicRadarDisplayTest.java
  src/test/java/models/flightTest/FlightTest.java
  src/test/java/models/statesTest/InAirStateTest.java
  src/test/java/models/statesTest/LandingModeStateTest.java
  src/test/java/models/statesTest/OnRunwayStateTest.java
  src/test/java/views/ConsoleLoggerTest.java
  src/test/java/views/SimulatorViewTest.java
  src/test/java/weatherPubSubTest/WeatherStationTest.java
  target/classes/logOutput/logfileOutput.log.lck
  target/jacoco.exec
  target/maven-archiver/pom.properties
  target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/createdFiles.lst
  target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
  target/surefire-reports/AutomatedTest.txt
  target/surefire-reports/TEST-AutomatedTest.xml
Labels: large

#46 Added colours to enum
  src/main/java/views/ConsoleColour.java
  src/main/java/views/ConsoleLogger.java
Labels: enhancement, small
